### ISSUE TITLE
Python error when trying to validate template.yaml

### ISSUE THREAD

**Issue by smorehouse** [pahud/sam-cli-docker#1]
Hello. When I try to validate my template.yaml I get the following stacktrace: 
```
~/Sunfish $ sam validate -t template.yaml --region us-east-1 --debug
Traceback (most recent call last):
  File "/usr/local/bin/sam", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/samcli/lib/telemetry/metrics.py", line 48, in wrapped
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/samcli/commands/validate/validate.py", line 27, in cli
    do_cli(ctx, template_file)  # pragma: no cover
  File "/usr/local/lib/python3.8/site-packages/samcli/commands/validate/validate.py", line 47, in do_cli
    validator.is_valid()
  File "/usr/local/lib/python3.8/site-packages/samcli/commands/validate/lib/sam_template_validator.py", line 60, in is_valid
    template = sam_translator.translate(sam_template=self.sam_template, parameter_values={})
  File "/usr/local/lib/python3.8/site-packages/samtranslator/translator/translator.py", line 89, in translate
    sam_parameter_values.add_pseudo_parameter_values()
  File "/usr/local/lib/python3.8/site-packages/samtranslator/sdk/parameter.py", line 73, in add_pseudo_parameter_values
    if region.startswith("cn-"):
AttributeError: 'NoneType' object has no attribute 'startswith'
```
I can validate this yaml in cloud9 and my local system, any ideas why it isn't working in the docker container? I also noticed you don't have git installed so you cannot "sam init" in the container as well. Are there other known limitations of the container?

**Comment by jewelsjacobs** [comment]
Hi there. Great work! Can you please. merge, tag and push this to dockerhub so I can use the update? It would be much appreciated :)
